### ISSUE TITLE
Gnome下字体发虚……显示异常

### ISSUE THREAD

**Issue by hetaozdh** [vufa/deepin-wine-tim-arch#118]
Gnome下字体渲染会长成这B样：
![image](https://user-images.githubusercontent.com/53343436/126980369-47d65496-a492-4c72-a377-d8354ce0b436.png)
修改注册表之后，容器内的regedit、winecfg字体都显示正常，TIM还是这样。

**Comment by thathuhao** [comment]
Same here.

**Comment by countstarlight** [comment]
这是系统里安装了宋体（simsun.ttc）吗

**Comment by vufa** [comment]
参照 [README: 字体发虚/使用其他字体](https://github.com/vufa/deepin-wine-tim-arch#%E5%AD%97%E4%BD%93%E5%8F%91%E8%99%9A%E4%BD%BF%E7%94%A8%E5%85%B6%E4%BB%96%E5%AD%97%E4%BD%93) 试试
