### ISSUE TITLE
deepin-wine5 aur仓库所依赖的deepin-udis86有问题

### ISSUE THREAD

**Issue by XiaoHuoZZ** [vufa/deepin-wine-tim-arch#119]
在运行切换deepin-wine5脚本时，无法正确安装deepin-wine5，目前貌似是所依赖的aur deepin-udis86版本出了问题, 总之目前无法通过aur源安装deepin-wine5

**Comment by cyqsimon** [comment]
```
Building deepin-udis86...
==> Making package: deepin-udis86 1.72_2-3 (Sat 21 Aug 2021 05:09:37 CST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading udis86_1.72-2_i386.deb...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0   146    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
==> ERROR: Failure while downloading https://community-packages.deepin.com/deepin/pool/non-free/u/udis86/udis86_1.72-2_i386.deb
    Aborting...
Failed to build deepin-udis86
```

**Comment by countstarlight** [comment]
安装 `deepin-udis86` 失败是因为 aur仓库 [deepin-udis86](https://aur.archlinux.org/packages/deepin-udis86/) 需要更新，[archlinuxcn](https://mirror.tuna.tsinghua.edu.cn/help/archlinuxcn/)源里有打包好的[deepin-udis86-1.72_2-3-x86_64.pkg.tar.xz](https://mirrors.tuna.tsinghua.edu.cn/archlinuxcn/x86_64/deepin-udis86-1.72_2-3-x86_64.pkg.tar.xz)，可以下载安装包或从源里安装

**Comment by cyqsimon** [comment]
@countstarlight thank you. I downloaded `deepin-udis-1.72_2-3-x86_64.pkg.tar.xz` and installed it manually before proceeding to build `deepin-wine-tim` from AUR. Build was successful.

**Comment by ayasa520** [comment]
镜像站里的deepin-udis86被删除了，https://github.com/JohnMasoner/deepin-udis86得在这儿手动安
