### ISSUE TITLE
Archlinux在构建时出错，是我缺少什么东西吗

### ISSUE THREAD

**Issue by Oveln** [vufa/deepin-wine-tim-arch#124]
==> Extracting Deepin Wine QQ archive ...

7-Zip [64] 17.04 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.04 (locale=C,Utf16=off,HugeFiles=on,64 bits,8 CPUs x64)

Scanning the drive for archives:
1 file, 110786919 bytes (106 MiB)
Extracting archive: /home/oveln/.cache/yay/deepin-wine-qq/src/dpkgdir/opt/apps/com.qq.im.deepin/files/files.7z

Path = /home/oveln/.cache/yay/deepin-wine-qq/src/dpkgdir/opt/apps/com.qq.im.deepin/files/files.7z
Type = 7z
Physical Size = 110786919
Headers Size = 22662
Method = LZMA2:26 BCJ2
Solid = +
Blocks = 1

ERROR: Can not delete output folder : No such file or directory : /home/oveln/.cache/yay/deepin-wine-qq/src/deepinqqdir/drive_c/Program Files/Tencent/QQ/?
ERROR: Can not delete output folder : No such file or directory : /home/oveln/.cache/yay/deepin-wine-qq/src/deepinqqdir/drive_c/Program Files/Tencent/QQ/??
ERROR: Can not delete output file : No such file or directory : /home/oveln/.cache/yay/deepin-wine-qq/src/deepinqqdir/drive_c/users/@current_user@/Application Data/Tencent/QQ/Misc/ClientType/???12.png
ERROR: Can not delete output file : No such file or directory : /home/oveln/.cache/yay/deepin-wine-qq/src/deepinqqdir/drive_c/users/@current_user@/Application Data/Tencent/QQ/Misc/ClientType/???12.png
ERROR: Can not delete output file : No such file or directory : /home/oveln/.cache/yay/deepin-wine-qq/src/deepinqqdir/drive_c/users/@current_user@/Application Data/Tencent/QQ/Misc/ClientType/???12.png
ERROR: Can not delete output file : No such file or directory : /home/oveln/.cache/yay/deepin-wine-qq/src/deepinqqdir/drive_c/users/@current_user@/Application Data/Tencent/QQ/Misc/ClientType/???12.png
ERROR: Can not delete output file : No such file or directory : /home/oveln/.cache/yay/deepin-wine-qq/src/deepinqqdir/drive_c/users/@current_user@/Application Data/Tencent/QQ/Misc/ClientType/???12.png
ERROR: Can not delete output file : No such file or directory : /home/oveln/.cache/yay/deepin-wine-qq/src/deepinqqdir/drive_c/users/@current_user@/Application Data/Tencent/QQ/Misc/ClientType/???12.png
ERROR: Can not delete output file : No such file or directory : /home/oveln/.cache/yay/deepin-wine-qq/src/deepinqqdir/drive_c/users/@current_user@/Application Data/Tencent/QQ/Misc/ClientType/???12.png
ERROR: Can not delete output file : No such file or directory : /home/oveln/.cache/yay/deepin-wine-qq/src/deepinqqdir/drive_c/users/@current_user@/Application Data/Tencent/QQ/Misc/ClientType/???12.png
ERROR: Can not delete output file : No such file or directory : /home/oveln/.cache/yay/deepin-wine-qq/src/deepinqqdir/drive_c/users/@current_user@/Application Data/Tencent/QQ/Misc/ClientType/????12.png
ERROR: Can not delete output file : No such file or directory : /home/oveln/.cache/yay/deepin-wine-qq/src/deepinqqdir/drive_c/users/@current_user@/Application Data/Tencent/QQ/Misc/ClientType/???12.png
ERROR: Can not delete output file : No such file or directory : /home/oveln/.cache/yay/deepin-wine-qq/src/deepinqqdir/drive_c/users/@current_user@/Application Data/Tencent/QQ/Misc/ClientType/???12.png
ERROR: Can not delete output file : No such file or directory : /home/oveln/.cache/yay/deepin-wine-qq/src/deepinqqdir/drive_c/users/@current_user@/Application Data/Tencent/QQ/Misc/ClientType/???12.png
ERROR: Can not delete output file : No such file or directory : /home/oveln/.cache/yay/deepin-wine-qq/src/deepinqqdir/drive_c/users/@current_user@/Application Data/Tencent/QQ/Misc/ClientType/???12.png
ERROR: Can not delete output file : No such file or directory : /home/oveln/.cache/yay/deepin-wine-qq/src/deepinqqdir/drive_c/users/@current_user@/Application Data/Tencent/QQ/Misc/ClientType/???12.png
ERROR: Can not delete output file : No such file or directory : /home/oveln/.cache/yay/deepin-wine-qq/src/deepinqqdir/drive_c/users/@current_user@/Application Data/Tencent/QQ/Misc/ClientType/???12.png

Sub items Errors: 17

Archives with Errors: 1

Sub items Errors: 17
==> ERROR: A failure occurred in build().
Aborting...
生成时出错: deepin-wine-qq

**Comment by countstarlight** [comment]
参照 https://github.com/countstarlight/deepin-wine-tim-arch/issues/116#issuecomment-877584643 试试
