### ISSUE TITLE
release中的3.8.22043-2版本依然提示需要deepin-wine6-stable

### ISSUE THREAD

**Issue by arklee** [vufa/deepin-wine-tim-arch#132]
安装提示如下：

sudo pacman -U deepin-wine-tim-3.3.8.22043-2-x86_64.pkg.tar.zst
loading packages...
warning: deepin-wine-tim-3.3.8.22043-2 is up to date -- reinstalling
resolving dependencies...
warning: cannot resolve "deepin-wine6-stable", a dependency of "deepin-wine-tim"
:: The following package cannot be upgraded due to unresolvable dependencies:
      deepin-wine-tim

:: Do you want to skip the above package for this upgrade? [y/N] n
error: failed to prepare transaction (could not satisfy dependencies)
:: unable to satisfy dependency 'deepin-wine6-stable' required by deepin-wine-tim

从AUR构建的没问题

**Comment by vufa** [comment]
已经更新：https://github.com/vufa/deepin-wine-tim-arch/commit/74be9dcf82ab19a9ec66f9440120527f70b54936
