### ISSUE TITLE
字体发虚

### ISSUE THREAD

**Issue by a15355447898a** [vufa/deepin-wine-tim-arch#135]
![FS98A D VS8~UDAFZI3(L_N](https://user-images.githubusercontent.com/62456287/148670252-a391f7a2-73f8-446b-a9be-23faf8d9f578.png)
按照网上给的命令: env WINEPREFIX="$HOME/.deepinwine/Deepin-TIM" winecfg 提示没有winecfg这个命令
使用 env WINEPREFIX="$HOME/.deepinwine/Deepin-TIM" deepin5-winecfg
提示 00e0:err:module:__wine_process_init L"C:\\windows\\system32\\deepin5-winecfg.exe" not found

**Comment by vufa** [comment]
参照 [README: 字体发虚/使用其他字体](https://github.com/vufa/deepin-wine-tim-arch#%E5%AD%97%E4%BD%93%E5%8F%91%E8%99%9A%E4%BD%BF%E7%94%A8%E5%85%B6%E4%BB%96%E5%AD%97%E4%BD%93) 试试

**Comment by a15355447898a** [comment]
问题解决,谢谢!
