### ISSUE TITLE
窗体周围有一圈黑框

### ISSUE THREAD

**Issue by a15355447898a** [vufa/deepin-wine-tim-arch#138]
![$KY1291Y _76K60($%FJQ}Q](https://user-images.githubusercontent.com/62456287/152529763-db21ac73-baa5-417a-b6b1-a6f5e630a868.png)
另:为什么每次打开tim,/usr/Lib/baloo file这个进程占用的CPU就飙升,害得我TIM卡死(KDE桌面)

**Comment by a15355447898a** [comment]
已解决,kde混成器没有开的原因

**Comment by misaka19465** [comment]
baloo和qq没有直接关系，baloo是提供搜索时的索引的，参见[ArchWiki](https://wiki.archlinux.org/title/Baloo)
