### ISSUE TITLE
TIM出现安全组件异常

### ISSUE THREAD

**Issue by flemon-y** [vufa/deepin-wine-tim-arch#139]
Linux：Manjaro GNOME
用Github源码安装
安装完成后打开出现这问题
![gnome-shell-screenshot-ffpt3r](https://user-images.githubusercontent.com/85869414/153117174-627fde3f-d185-408e-bc95-e49c61af3330.png)

**Comment by vufa** [comment]
与 https://github.com/countstarlight/deepin-wine-tim-arch/issues/90 重复
