### ISSUE TITLE
yay安装deepin-wine-tim生成时错误

### ISSUE THREAD

**Issue by FrozenArcher** [vufa/deepin-wine-tim-arch#143]
archlinux, kde.

...（都是类似的错误）
ERROR: Can not delete output file : No such file or directory : /home/fracher/.cache/yay/deepin-wine-tim/src/deepintimdir/drive_c/users/@current_user@/Application Data/Tencent/QQ/Misc/ClientType/???12.png

Sub items Errors: 17

Archives with Errors: 1

Sub items Errors: 17
==> ERROR: A failure occurred in build().
    Aborting...
 -> 生成时出错: deepin-wine-tim

安装deepin-wine-qq时也一样。

**Comment by FrozenArcher** [comment]
> 

清理了，没啥用。这个问题和wine有关吗？

**Comment by KenMizz** [comment]
我也出现了该问题。。
