### ISSUE TITLE
第一次安装后无法再次启动

### ISSUE THREAD

**Issue by DissolveBoi** [vufa/deepin-wine-tim-arch#144]
默认路径安装后启动正常，可以通过``wincfg``来进行相关配置
但``winecfg``后提示``Wine cannot find the ncurses library (libncurses.so.6).``

在退出后无法二次启动，遂尝试在``/opt/apps/com.qq.office.deepin/files/``直接运行``run.sh``
终端显示：
```
/opt/deepinwine/tools/run_v4.sh: 第 135 行：cd: /home/*****/.deepinwine/Deepin-TIM/drive_c/Program Files/Tencent/TIM/Bin: 没有那个文件或目录
/opt/apps/com.qq.office.deepin/files
wine: cannot find 'c:/Program Files/Tencent/TIM/Bin/TIM.exe'
```
已经尝试了替换原装的``simsun``字体和修改并替换``dwrite.dll``的相关配置，并无作用。

**Comment by vufa** [comment]
> wine: cannot find 'c:/Program Files/Tencent/TIM/Bin/TIM.exe'

删除安装目录再试：
```bash
rm -rf ~/.deepinwine/Deepin-TIM
```
不要修改默认路径

**Comment by inuxor** [comment]
我是一次都没能启动成功，错误同顶楼
安装过程并未做任何更改。
观察发现：通过终端运行 "/opt/apps/com.qq.office.deepin/files/run.sh"安装，默认安装位置的虚拟盘符为Y
```
wine version: 5.0
Could not find Wine Gecko. HTML rendering will be disabled.
wine: configuration in L"Y:\\.deepinwine\\Deepin-TIM" has been updated.

```
安装完成后在~/.deepinwine/Deepin-TIM/drive_c/Program Files/Tencent/目录下并未生成Tim目录

通过桌面图标启动安装脚本的虚拟盘符为C,正确生成TIM目录
然而再次通过桌面图标启动，会删除已经生成的TIM目录。。。。

**Comment by xsm1997** [comment]
最新版本deepin-wine-helper的问题，从源码构建降级安装后可以正常运行。

**Comment by vufa** [comment]
已经添加修复( https://github.com/vufa/deepin-wine-tim-arch/commit/30da3eb3a1664a8bbae074c448faaf9f56627f3d )，尝试从AUR安装最新版

**Comment by Exlog42** [comment]
最新版本还是有这个问题
