### ISSUE TITLE
2.3.1_3-4 版不显示中文字符，无法正常使用

### ISSUE THREAD

**Issue by chenjunyu19** [vufa/deepin-wine-tim-arch#23]
![_ _20190206091302](https://user-images.githubusercontent.com/15167799/52314863-6e8a7100-29ef-11e9-9c97-a32ff2b88085.png)

如题。登录成功后，会发现中文字符要么消失，要么变成方框，随即 TIM 自己崩溃。

删除容器（`~/.deepinwine/Deepin-TIM`）重新安装无效。

```
$ pacman -Q wine deepin-wine-tim fontconfig noto-fonts-cjk adobe-source-han-sans-cn-fonts wqy-microhei 
wine 4.0-2
deepin-wine-tim 2.3.1_3-4
fontconfig 2:2.13.1+12+g5f5ec56-1
noto-fonts-cjk 20181130-2
adobe-source-han-sans-cn-fonts 2.000-2
wqy-microhei 0.2.0_beta-9
```

**Comment by countstarlight** [comment]
直接运行：
```shell
/opt/deepinwine/apps/Deepin-TIM/run.sh
```
触发崩溃，看看有什么输出

**Comment by chenjunyu19** [comment]
[output.txt](https://github.com/countstarlight/deepin-wine-tim-arch/files/2834740/output.txt)

**Comment by countstarlight** [comment]
@chenjunyu19 刚才向AUR推送了更新，安装试试问题有没有解决：
```shell
yaourt deepin-wine-tim
```
注意选择AUR，archlinuxcn源还没有更新

**Comment by chenjunyu19** [comment]
在外吃饭，稍等下哈。另外提下，`yaourt` 疑似已经被弃坑了，`yay`了解下。

**Comment by chenjunyu19** [comment]
> @chenjunyu19 刚才向AUR推送了更新，安装试试问题有没有解决：
> 
> ```shell
> yaourt deepin-wine-tim
> ```
> 
> 注意选择AUR，archlinuxcn源还没有更新

版本 `2.3.1_3-5` 问题依旧。

**Comment by countstarlight** [comment]
@chenjunyu19 `2.3.1_3-5`在新装的archlinux虚拟机里测试没有问题，尝试完全卸载：
```shell
sudo pacman -Rns deepin-wine-tim
```
再安装试试

**Comment by chenjunyu19** [comment]
手动导入注册表仍然无效。

**Comment by countstarlight** [comment]
建议先降级`deepin-wine-tim`或尝试安装`deepin-wine-qq`，等等看有没有其他反馈。

**Comment by jerryshell** [comment]
> @chenjunyu19 `2.3.1_3-5`在新装的archlinux虚拟机里测试没有问题，尝试完全卸载：
> 
> ```shell
> sudo pacman -Rns deepin-wine-tim
> ```
完全卸载然后重新安装后问题解决
![screenshot_20190207_203822](https://user-images.githubusercontent.com/17442603/52412032-90cbde00-2b18-11e9-85b6-96c15cb2dea4.png)

**Comment by de-conf** [comment]
2.3.1_3-5 问题依旧(不显示中文字符，登录崩溃，上述解决办法无效，运行 `/opt/deepinwine/apps/Deepin-TIM/run.sh` 日志如下


[log.txt](https://github.com/countstarlight/deepin-wine-tim-arch/files/2849842/log.txt)

**Comment by chenjunyu19** [comment]
从 Windows 拷了一个`宋体`过来，字体能正常显示，不过崩溃照常。字体应该不是什么大事。（GIF 较大，3M。）
![_ _20190212183744 mp4](https://user-images.githubusercontent.com/15167799/52629936-d102d600-2ef5-11e9-9849-7c0b35445b97.gif)

**Comment by nujabse** [comment]
同是 arch 使用 yaourt 升级之后，就会出现这种状况。 同样是完全删除之后再安装就好了

**Comment by countstarlight** [comment]
@chenjunyu19 按照你的描述调整了一下注册表，完全删除再从AUR安装试试能不能解决。

**Comment by yunshang** [comment]
![screenshot_20190219_095324](https://user-images.githubusercontent.com/5956306/52984904-6dfccc00-342c-11e9-9dd8-c5c076a2b43f.png)
这个会是什么原因，我卸载了重新安装也还是不行。

**Comment by chenjunyu19** [comment]
> @chenjunyu19 按照你的描述调整了一下注册表，完全删除再从AUR安装试试能不能解决。

@countstarlight 字体良好，崩溃照常。

（其实手动替换注册表文件也行啊，没必要重新打包，耗时

（开学了，周六上午才放学，抱歉让你久等了

**Comment by chenjunyu19** [comment]
另外还有就是这个渲染比较神奇（243k GIF），需要一些特定的操作才能刷新控件渲染，除了登录界面，在其他地方也有这种现象。
![_ _20190223105222 mp4](https://user-images.githubusercontent.com/15167799/53280787-5f2e5600-3759-11e9-9a53-6c969b39397c.gif)

**Comment by i6o6i** [comment]
我也遇到一样的问题,后来一句
    ln -s /usr/lib32/dri/i965_dri.so /usr/lib32/xorg/modules/dri/
解决了，系统是arch，双显卡（之前一直提示和OpenGL相关的错误，建议在运行前先执行"export LIBGL_DEBUG=verbose"）

**Comment by countstarlight** [comment]
@i6o6i 感谢帮助，我去研究一下

**Comment by nonamestreet** [comment]
我也是同样的问题，拷贝了字体好像也没用。

**Comment by de-conf** [comment]
2.3.2.21173-1版本依旧不显示字体,并且登录后崩溃
![image](https://user-images.githubusercontent.com/26062629/67390648-a95d2500-f5cf-11e9-945a-d6ceda05a6cb.png)

**Comment by fratcn** [comment]
同问，就是换deepin-wine的问题
